add build requirement for centos 8
creating debug packages requires gdb-add-index which is in package gdb-headless. Results in
```
ERROR: GDB index requested, but no gdb-add-index installed
```
otherwise.